package com.vector.verevcodex.presentation.programs

internal const val PROGRAM_FIELD_NAME = "name"
internal const val PROGRAM_FIELD_DESCRIPTION = "description"
internal const val PROGRAM_FIELD_TARGET_AGE_MIN = "target_age_min"
internal const val PROGRAM_FIELD_TARGET_AGE_MAX = "target_age_max"
internal const val PROGRAM_FIELD_SCHEDULE_START = "schedule_start"
internal const val PROGRAM_FIELD_SCHEDULE_END = "schedule_end"
internal const val PROGRAM_FIELD_SCHEDULE_REPEAT = "schedule_repeat"
internal const val PROGRAM_FIELD_BENEFIT_RESET_CUSTOM_DAYS = "benefit_reset_custom_days"
internal const val PROGRAM_FIELD_POINTS_STEP = "points_step"
internal const val PROGRAM_FIELD_POINTS_AWARDED = "points_awarded"
internal const val PROGRAM_FIELD_POINTS_REDEEM = "points_redeem"
internal const val PROGRAM_FIELD_CASHBACK_PERCENT = "cashback_percent"
internal const val PROGRAM_FIELD_TIER_SILVER = "tier_silver"
internal const val PROGRAM_FIELD_TIER_GOLD = "tier_gold"
internal const val PROGRAM_FIELD_TIER_VIP = "tier_vip"
internal const val PROGRAM_FIELD_COUPON_NAME = "coupon_name"
internal const val PROGRAM_FIELD_COUPON_POINTS = "coupon_points"
internal const val PROGRAM_FIELD_COUPON_DISCOUNT = "coupon_discount"
internal const val PROGRAM_FIELD_CHECKIN_VISITS = "checkin_visits"
internal const val PROGRAM_FIELD_CHECKIN_REWARD = "checkin_reward"
internal const val PROGRAM_FIELD_FREQUENCY_COUNT = "frequency_count"
internal const val PROGRAM_FIELD_FREQUENCY_WINDOW = "frequency_window"
internal const val PROGRAM_FIELD_FREQUENCY_REWARD = "frequency_reward"
internal const val PROGRAM_FIELD_REFERRAL_REFERRER = "referral_referrer"
internal const val PROGRAM_FIELD_REFERRAL_REFEREE = "referral_referee"
internal const val PROGRAM_FIELD_REFERRAL_PREFIX = "referral_prefix"
