package com.vector.verevcodex.data.repository.reports

import com.vector.verevcodex.domain.model.reports.ReportFormat
import java.io.File
import java.io.FileOutputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

internal object ReportFileWriter {
    fun write(outputDir: File, fileName: String, format: ReportFormat, document: ReportDocument): File {
        outputDir.mkdirs()
        val file = File(outputDir, fileName)
        when (format) {
            ReportFormat.DOCX -> writeDocx(file, document)
            ReportFormat.XLSX -> writeXlsx(file, document)
            ReportFormat.PDF -> throw UnsupportedOperationException("PDF reports are generated by the backend")
        }
        return file
    }

    private fun writeDocx(file: File, document: ReportDocument) {
        ZipOutputStream(FileOutputStream(file)).use { zip ->
            zip.writeEntry(
                "[Content_Types].xml",
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
                    <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
                    <Default Extension="xml" ContentType="application/xml"/>
                    <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
                    <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
                    <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
                </Types>
                """.trimIndent(),
            )
            zip.writeEntry(
                "_rels/.rels",
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
                    <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
                    <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
                    <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
                </Relationships>
                """.trimIndent(),
            )
            zip.writeEntry(
                "docProps/core.xml",
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                    <dc:title>${xml(document.title)}</dc:title>
                    <dc:creator>Verev Business</dc:creator>
                    <cp:lastModifiedBy>Verev Business</cp:lastModifiedBy>
                </cp:coreProperties>
                """.trimIndent(),
            )
            zip.writeEntry(
                "docProps/app.xml",
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
                    <Application>Verev Business</Application>
                </Properties>
                """.trimIndent(),
            )
            zip.writeEntry(
                "word/document.xml",
                buildString {
                    append("""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>""")
                    append("""<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>""")
                    append(paragraph(document.title, bold = true))
                    append(paragraph(document.subtitle))
                    append(paragraph(document.summary))
                    document.sections.forEach { section ->
                        append(paragraph(section.title, bold = true))
                        section.rows.forEach { (label, value) ->
                            append(paragraph("$label: $value"))
                        }
                    }
                    append("""<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr>""")
                    append("</w:body></w:document>")
                },
            )
        }
    }

    private fun writeXlsx(file: File, document: ReportDocument) {
        val rows = mutableListOf<List<String>>()
        rows.add(listOf(document.title))
        rows.add(listOf(document.subtitle))
        rows.add(listOf(document.summary))
        rows.add(emptyList())
        document.sections.forEach { section ->
            rows.add(listOf(section.title))
            section.rows.forEach { (label, value) ->
                rows.add(listOf(label, value))
            }
            rows.add(emptyList())
        }

        ZipOutputStream(FileOutputStream(file)).use { zip ->
            zip.writeEntry(
                "[Content_Types].xml",
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
                    <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
                    <Default Extension="xml" ContentType="application/xml"/>
                    <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
                    <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
                    <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
                    <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
                </Types>
                """.trimIndent(),
            )
            zip.writeEntry(
                "_rels/.rels",
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
                    <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
                    <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
                    <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
                </Relationships>
                """.trimIndent(),
            )
            zip.writeEntry(
                "docProps/core.xml",
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/">
                    <dc:title>${xml(document.title)}</dc:title>
                    <dc:creator>Verev Business</dc:creator>
                </cp:coreProperties>
                """.trimIndent(),
            )
            zip.writeEntry(
                "docProps/app.xml",
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
                    <Application>Verev Business</Application>
                </Properties>
                """.trimIndent(),
            )
            zip.writeEntry(
                "xl/workbook.xml",
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
                    <sheets>
                        <sheet name="Report" sheetId="1" r:id="rId1"/>
                    </sheets>
                </workbook>
                """.trimIndent(),
            )
            zip.writeEntry(
                "xl/_rels/workbook.xml.rels",
                """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
                    <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
                </Relationships>
                """.trimIndent(),
            )
            zip.writeEntry(
                "xl/worksheets/sheet1.xml",
                buildString {
                    append("""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>""")
                    append("""<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>""")
                    rows.forEachIndexed { rowIndex, row ->
                        append("""<row r="${rowIndex + 1}">""")
                        row.forEachIndexed { cellIndex, cell ->
                            val ref = cellRef(cellIndex, rowIndex + 1)
                            append("""<c r="$ref" t="inlineStr"><is><t>${xml(cell)}</t></is></c>""")
                        }
                        append("</row>")
                    }
                    append("</sheetData></worksheet>")
                },
            )
        }
    }

    private fun ZipOutputStream.writeEntry(path: String, content: String) {
        putNextEntry(ZipEntry(path))
        write(content.toByteArray(Charsets.UTF_8))
        closeEntry()
    }

    private fun paragraph(text: String, bold: Boolean = false): String {
        val runProps = if (bold) "<w:rPr><w:b/></w:rPr>" else ""
        return """<w:p><w:r>$runProps<w:t xml:space="preserve">${xml(text)}</w:t></w:r></w:p>"""
    }

    private fun xml(value: String): String = value
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;")
        .replace("'", "&apos;")

    private fun cellRef(columnIndex: Int, rowIndex: Int): String {
        var dividend = columnIndex + 1
        var label = ""
        while (dividend > 0) {
            val modulo = (dividend - 1) % 26
            label = ('A'.code + modulo).toChar() + label
            dividend = (dividend - modulo) / 26
        }
        return "$label$rowIndex"
    }
}
