package com.vector.verevcodex.domain.model.customer

enum class CustomerBonusActionType {
    DISCOUNT_APPLIED,
    TIER_BENEFIT_RECORDED,
    MANUAL_VISITS_ADDED,
    MANUAL_VISITS_REMOVED,
    MANUAL_POINTS_ADDED,
    MANUAL_POINTS_REMOVED,
    CUSTOMER_ENROLLED,
    CUSTOMER_LINKED,
    CUSTOMER_LINKED_BY_SUPPORT,
    CUSTOMER_SPLIT_BY_SUPPORT,
    CHECK_IN,
    CHECK_IN_REWARD,
    REFERRAL_REFERRER_REWARD,
    REFERRAL_REFEREE_REWARD,
    PURCHASE_FREQUENCY_REWARD,
    OTHER,
}
